# Coolify Configuration
# This file helps Coolify understand the project structure

version: '1.0'

# Application configuration
application:
  name: tradanalisa
  type: docker-compose
  
# Build configuration
build:
  compose_files:
    - docker-compose.yml
    - frontend/docker-compose.prod.yml
  context: .
  
# Port configuration
ports:
  - 3000

# Health check
healthcheck:
  service: backend
  path: /health
  interval: 30
  timeout: 10
  retries: 3

# Environment variables (set these in Coolify dashboard)
environment:
  - NEXT_PUBLIC_API_URL
  - DATABASE_URL
  - JWT_SECRET_KEY
  - BINANCE_API_KEY
  - BINANCE_API_SECRET
  - OPENROUTER_API_KEY
